version: 2.1

jobs: 
  fluidattacks:
    docker: 
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout
      - run: 
          name: Setup Prerequisites
          command: |
            sudo apt update
            sudo apt -y install csvkit
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Verify Configuration
          command: |
            mv /root/project/.circleci/casa/config.yaml /root/project/config.yaml
      - run:
          name: Run CASA SAST scan
          command: |
            sudo docker run -v /home/circleci/project:/workingdir m gitlab:fluidattacks/universe@trunk /skims scan ./config.yaml
      - run:
          name: Prepare Results for DefectDojo
          command: |
            mv /root/projects/.circleci/casa/format.sh /root/project/format.sh
            sh /root/project/format.sh

workflows:
  security_flow:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      [fluidattacks]
