version: 2.1

jobs:
  trivy:
    docker:
      - image: aquasec/trivy:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: Trivy scan
          command: |
            trivy rootfs --scanners config,vuln,secret,license --format json --output /tmp/trivy.json --no-progress --ignore-unfixed /root/project
      - persist_to_workspace:
          root: /tmp
          paths:
            - trivy.json
  fluidattacks:
    docker: 
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Setup Prerequisites
          command: |
            sudo apt update
            sudo apt -y install csvkit
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Verify Configuration
          command: |
            mv ~/project/.circleci/casa/config.yaml ~/project/config.yaml
      - run:
          name: Setup Fluidattacks
          command: |
            docker create -v /working-dir --name repo alpine:3.4 /bin/true
            docker cp /home/circleci/project repo:/working-dir
      - run:
          name: Run CASA SAST scan
          command: |
            docker run --volumes-from repo --name fluidattacks ghcr.io/fluidattacks/makes/amd64 m gitlab:fluidattacks/universe@trunk /skims scan project/config.yaml
      - run:
          name: Copy results from Fluidattacks container
          command: |
            docker cp fluidattacks:/working-dir/Fluid-Attacks-Results.csv .
      - run:
          name: Prepare Results for DefectDojo
          command: |
            mv /home/circleci/project/.circleci/casa/format.sh /home/circleci/project/format.sh
            sh /home/circleci/project/format.sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - output.csv
  zap:
    docker:
      - image: owasp/zap2docker-live:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: Zap Application Scan
          command: |
            zap-baseline.py -t https://www.example.com -x /tmp/zap.xml
      - persist_to_workspace:
          root: /tmp
          paths:
            - zap.xml
  defectdojo:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: View Trivy Scan data
          command: |
            cat /tmp/trivy.json
            cat zap.xml

workflows:
  security_flow:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - trivy
      - zap
      #- fluidattacks
      - defectdojo:
          requires:
            - trivy
            - zap
