version: 2.1

jobs:
  trivy:
    docker:
      - image: aquasec/trivy:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: Trivy scan
          command: |
            trivy rootfs --scanners config,vuln,secret,license --format json --output /tmp/trivy.json --no-progress --ignore-unfixed /root/project
      - persist_to_workspace:
          root: /tmp
          paths:
            - trivy.json
  fluidattacks:
    docker: 
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Setup Prerequisites
          command: |
            sudo apt update
            sudo apt -y install csvkit
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Verify Configuration
          command: |
            mv ~/project/.circleci/casa/config.yaml ~/project/config.yaml
      - run:
          name: Setup Fluidattacks
          command: |
            docker create -v /working-dir --name repo alpine:3.4 /bin/true
            docker cp /home/circleci/project repo:/working-dir
      - run:
          name: Run CASA SAST scan
          command: |
            docker run --volumes-from repo --name fluidattacks ghcr.io/fluidattacks/makes/amd64 m gitlab:fluidattacks/universe@trunk /skims scan project/config.yaml
      - run:
          name: Copy results from Fluidattacks container
          command: |
            docker cp fluidattacks:/working-dir/Fluid-Attacks-Results.csv .
      - run:
          name: Prepare Results for DefectDojo
          command: |
            mv /home/circleci/project/.circleci/casa/format.sh /home/circleci/project/format.sh
            sh /home/circleci/project/format.sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - output.csv
  defectdojo:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run:
          name: Post Scan to DefectDojo
          command: |
            curl -X POST -F "scan_type=Bandit Scan" -F "engagement=1" -F "scan_date=$(date +%Y-%m-%d)" -F "file=@/tmp/fluidattacks/output.csv" -H "Authorization: Token ${DOJO_TOKEN}" ${DOJO_URL}/api/v2/import-scan/

workflows:
  security_flow:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - trivy
      #- fluidattacks
      #- defectdojo:
      #    requires:
      #      - fluidattacks
