version: 2.1

jobs: 
  fluidattacks: 
    docker: 
      - image: ghcr.io/fluidattacks/makes/amd64
    resource_class: small
    steps:
      - checkout
      - run:
          name: Verify Configuration
          command: |
            mv ~/project/.circleci/casa/config.yaml ~/project/config.yaml
      - run:
          name: Run CASA SAST scan
          command: |
            m gitlab:fluidattacks/universe@trunk /skims scan project/config.yaml
workflows:
  security_flow:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      [fluidattacks]
