// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackupRepository(arg1) {
  return window['go']['main']['App']['CreateBackupRepository'](arg1);
}

export function DeployStacks(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeployStacks'](arg1, arg2, arg3, arg4, arg5);
}

export function DisconnectGitHub() {
  return window['go']['main']['App']['DisconnectGitHub']();
}

export function EmitProgress(arg1) {
  return window['go']['main']['App']['EmitProgress'](arg1);
}

export function EmitStatus(arg1, arg2) {
  return window['go']['main']['App']['EmitStatus'](arg1, arg2);
}

export function GetGitHubAuthStatus() {
  return window['go']['main']['App']['GetGitHubAuthStatus']();
}

export function GetModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetModel'](arg1, arg2, arg3);
}

export function InitiateGitHubAuth() {
  return window['go']['main']['App']['InitiateGitHubAuth']();
}

export function InstallDocker(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallDocker'](arg1, arg2, arg3, arg4);
}

export function InstallPortainer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallPortainer'](arg1, arg2, arg3, arg4);
}

export function PrepareNetworkCIFS(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['PrepareNetworkCIFS'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function PrepareNetworkNFS(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PrepareNetworkNFS'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PrepareUSB(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PrepareUSB'](arg1, arg2, arg3, arg4);
}

export function TestSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestSSH'](arg1, arg2, arg3);
}

export function UpdatePi(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePi'](arg1, arg2, arg3);
}
