// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateBackupRepository(arg1:string):Promise<void>;

export function DeployStacks(arg1:string,arg2:string,arg3:string,arg4:string,arg5:main.StackConfig):Promise<void>;

export function DisconnectGitHub():Promise<void>;

export function EmitProgress(arg1:string):Promise<void>;

export function EmitStatus(arg1:string,arg2:boolean):Promise<void>;

export function GetGitHubAuthStatus():Promise<main.GitHubAuthStatus>;

export function GetModel(arg1:string,arg2:string,arg3:string):Promise<string>;

export function InitiateGitHubAuth():Promise<void>;

export function InstallDocker(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InstallPortainer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PrepareNetworkCIFS(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function PrepareNetworkNFS(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function PrepareUSB(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TestSSH(arg1:string,arg2:string,arg3:string):Promise<main.ConnectionResult>;

export function UpdatePi(arg1:string,arg2:string,arg3:string):Promise<void>;
